# Generated by Django 6.0.3 on 2026-03-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_review_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='personal_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('playing', 'Playing'), ('completed', 'Completed'), ('backlog', 'Backlog'), ('dropped', 'Dropped')], default='backlog', max_length=20),
        ),
    ]
